from Listas_Circulares import CircularList

CL = CircularList()
print(f"cl esta vacia? {CL.is_empty()}\n")
CL.insert(10)
print(f"cl esta vacia? {CL.is_empty()}\n")
CL.insert(20)
CL.insert(11)
CL.insert(21)
CL.insert(1)
CL.insert(5)
CL.transversal()
CL.insert(-1)
CL.insert(0)
CL.insert(7)
CL.transversal()
CL.insert(7)
CL.transversal()
CL.get_size()
CL.insert(100)
CL.transversal()
CL.get_size()
CL.insert(-10)
CL.transversal()
CL.get_size()
CL.remove(100)
CL.transversal()
CL.get_size()
CL.remove(100)
CL.remove(200)
